# docker-image.yml
name: Publish Docker image   # workflow名称，可以在Github项目主页的【Actions】中看到所有的workflow
env:
  APP_NAME: java-dev
  DOCKERHUB_REPO: nriet/java-dev
  APP_VERSION: 1.15.0-rolling
on:   # 配置触发workflow的事件
  push:
    branches:   # master分支有push时触发此workflow
      - 'develop'
    tags:       # tag更新时触发此workflow
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # - 
        # name: Generate App Version
        # run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      # - name: openjdk-slim-buster
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: 8.5/jdk8/openjdk-slim-buster/.
      #     platforms: |
      #       linux/amd64
      #       linux/arm64
      #     push: true
      #     tags: |
      #       ${{ env.DOCKERHUB_REPO }}:latest
      #       ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-jdk8-openjdk-slim-buster
      - name: kasm-java-dev
        uses: docker/build-push-action@v2 # docker build  & push
        with:
          file: dockerfile-kasm-java-dev
          platforms: |
            linux/amd64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
        
      # - name: openjdk-slim-buster-python3
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: 8.5/jdk8/openjdk-slim-buster-python3/.
      #     platforms: |
      #       linux/amd64
      #       linux/arm64
      #     push: true
      #     tags: ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-jdk8-openjdk-slim-buster-python3
          
      # - name: openjdk-slim-buster-python3-fy4a
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: 8.5/jdk8/fy4a/.
      #     platforms: |
      #       linux/amd64
      #       linux/arm64
      #     push: true
      #     tags: ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}-jdk8-openjdk-slim-buster-python3-fy4a        